FROM node:24.4.1-bookworm-slim AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .

FROM dependencies AS host-build
ARG PUBLIC_PROVIDER_HOST=localhost
ARG PUBLIC_PROVIDER_REACT_URL
ARG PUBLIC_PROVIDER_SVELTE_URL
ARG PUBLIC_PROVIDER_RSC_URL
ARG PUBLIC_PROVIDER_SVELTE_SSR_URL
ARG PUBLIC_PROVIDER_HONO_URL
ARG PUBLIC_PROVIDER_NEXT_URL
ARG PUBLIC_PROVIDER_BLAZOR_URL
ARG PUBLIC_PROVIDER_PHOENIX_URL
ENV PUBLIC_PROVIDER_HOST=$PUBLIC_PROVIDER_HOST
ENV PUBLIC_PROVIDER_REACT_URL=$PUBLIC_PROVIDER_REACT_URL
ENV PUBLIC_PROVIDER_SVELTE_URL=$PUBLIC_PROVIDER_SVELTE_URL
ENV PUBLIC_PROVIDER_RSC_URL=$PUBLIC_PROVIDER_RSC_URL
ENV PUBLIC_PROVIDER_SVELTE_SSR_URL=$PUBLIC_PROVIDER_SVELTE_SSR_URL
ENV PUBLIC_PROVIDER_HONO_URL=$PUBLIC_PROVIDER_HONO_URL
ENV PUBLIC_PROVIDER_NEXT_URL=$PUBLIC_PROVIDER_NEXT_URL
ENV PUBLIC_PROVIDER_BLAZOR_URL=$PUBLIC_PROVIDER_BLAZOR_URL
ENV PUBLIC_PROVIDER_PHOENIX_URL=$PUBLIC_PROVIDER_PHOENIX_URL
RUN npm run build:host

FROM nginx:1.29.1-alpine AS host
COPY --from=host-build /app/host/dist /usr/share/nginx/html

FROM dependencies AS provider
ARG PROVIDER
ENV PROVIDER=$PROVIDER
ENV NEXT_TELEMETRY_DISABLED=1
RUN node scripts/build.mjs "$PROVIDER"
RUN if [ "$PROVIDER" = "next" ]; then npx next build providers/next; fi
CMD ["node", "scripts/serve.mjs"]
